version: "3"
services:
  web:
    build: ./webserv
    ports:
      - "8080:80"
    networks:
      - sae23net
    volumes:
      - ./site/:/var/www/html
  php:
    image: php:8.1-fpm
    networks:
      - sae23net
    volumes:
      - ./site/:/var/www/html
  pma:
    image: phpmyadmin
    ports:
      - "8081:80"
    networks:
      - sae23net
    links:
      - sql
    environment:
      PMA_HOST: sql
  sql:
    image: mysql
    networks:
      - sae23net
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db/:/var/lib/mysql
networks:
  sae23net:
    driver: bridge
