version: "3"
services:
  web:
    build: ./webserv
    ports:
      - "8080:80"
    networks:
      - sae23net
    volumes:
      - ./site/:/var/www/html
  php:
    build: ./phpserv
    networks:
      - sae23net
    volumes:
      - ./site/:/var/www/html
  pma:
    image: phpmyadmin
    ports:
      - "8081:80"
    networks:
      - sae23net
    links:
      - sql
    environment:
      PMA_HOST: sql
  sql:
    image: mariadb:10.0.38
    command: --character-set-server=utf8
    networks:
      - sae23net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Paris
    volumes:
      - ./db/:/var/lib/mysql
networks:
  sae23net:
    driver: bridge
